version: 2.2.1.{build}
image: Visual Studio 2019
configuration: Release
skip_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

environment:
  GoCardlessAccessToken:
    secure: TXXkPrAH2llzmiO+qkmAJrPWpYQ+5764Gz6z30AhhxAyc7rMJCDJl5hdRvS4lZKcpVc7wZVi1AiHBXAKjuxeSg==
  GoCardlessMerchantAccessToken:
    secure: G1bsYuWUcdrK8fgPSf7alrvlFjZWcs6lWJ4xzFusLXpN3uejuFUBCrCo89ln5tRqR7GWfbmNFRnWXe8sAQhbSg==

pull_requests:
  do_not_increment_build_number: true

before_build:
  dotnet restore

build:
  publish_nuget: true
  publish_nuget_symbols: false
  include_nuget_references: true
  verbosity: minimal

test:
  assemblies:
    GoCardless.Api.Tests.Unit.dll
    GoCardless.Api.Tests.Integration.dll

deploy:
  provider: NuGet
  api_key:
    secure: IHQBPznFGiXsWhZzJT3e6RPD062lPDeny7gZokkAfwc8nwBebVnJeeNBhzFIeK62
  skip_symbols: true
  on:
    branch: master